import "@/styles/globals.css";

import { Inter } from "next/font/google";
import NavBar from "@/components/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Gsap-Test",
  description: "Generated by T-messi",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`mx-0 bg-black font-sans text-white md:mx-5 ${inter.variable}`}
      >
        <div className="mx-auto my-10 flex min-h-screen max-w-[1200px] flex-col text-white">
          <NavBar />
          <main className="my-10">{children}</main>
          <NavBar />
        </div>
      </body>
    </html>
  );
}
